[package]
name = "starsoldier-bytecode"
version = "0.1.0"
authors = ["taotao54321 <taotao54321@gmail.com>"]
edition = "2018"

[dependencies]
eyre = "0.6.5"
logos = "0.12.0"
structopt = "0.3.21"
thiserror = "1.0.25"
